apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-application1
  labels:
    app: demo-application1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-application1
  template:
    metadata:
      labels:
        app: demo-application1
    spec:
      containers:
        - name: demo-application1
          image: gcr.io/my-kubernetes-project-389604/gke-deployment-ci-cd
          ports:
            - containerPort: 8080